function setup_path()
    path([pwd '/configuration'], path)
    path([pwd '/lib'], path)
    path([pwd '/coding'], path)
    path([pwd '/detection_equalization'], path)
    path([pwd '/packetizing'], path)
    path([pwd '/pulse_shaping'], path)
    path([pwd '/synchronization'], path)
    path([pwd '/testbench'], path)
    path([pwd '/file_utils'], path)
    path([pwd '/cyclo'], path)
    path([pwd '/channelize'], path)
    path([pwd '/runtime'], path)
end
