global CYCLO_AVERAGING
global CYC_SPEC_METHOD
global PACKETIZE
global CODING
global MODULATION
global PACKET_SIZE_BITS
global HEADER_SIZE_BITS
global GENERATING_POLYS
global CONSTRAINT_LENGTH
global RC_ROLLOFF
global PHASE_WINDOW
global COARSE_FFT_SIZE
global F_S
global SAMPLES_PER_SYMBOL
global DATA_SIZE_BITS
global T
global CODE_RATE
global M
global SYNC_PATTERN
global BITS_PER_SYMBOL
global PULSE_SHAPE
global PACKET_SIZE_SAMPLES

global CYCLO_PEAK_THRESH
global CYCLO_PEAK_MIN_SPACING

global DEBUG_FIGURES;
